from __future__ import annotations

from uuid import uuid4

from mini_rag.graph.state import AgentState
from mini_rag.security.permissions import normalize_role


def create_initial_state(
    question: str,
    session_id: str | None = None,
    retrieval_mode: str | None = None,
    enable_rerank: bool | None = None,
    user_id: str | None = None,
    role: str | None = None,
    trace_id: str | None = None,
    kb_ids: list[str] | None = None,
    override_now: str | None = None,
) -> AgentState:
    workflow_run_id = uuid4().hex
    return {
        "question": question,
        "user_query": question,
        "session_id": session_id,
        "user_id": user_id or "anonymous",
        "role": normalize_role(role),
        "workflow_run_id": workflow_run_id,
        "trace_id": trace_id or workflow_run_id,
        "retrieval_mode": retrieval_mode,
        "enable_rerank": enable_rerank,
        "requested_kbs": kb_ids or [],
        "allowed_kbs": [],
        "used_kbs": [],
        "override_now": override_now,
        "conversation_summary": "",
        "history": [],
        "intent": "",
        "message_type": "",
        "context_usage": "none",
        "available_capabilities": [],
        "goals": [],
        "goal_coverage": {},
        "runtime_context": {},
        "plan_state": {},
        "execution_state": {},
        "answer_state": {},
        "capability_catalog": {},
        "permissions": {},
        "planner_schema_version": "",
        "resolved_time_facts": [],
        "react_steps": [],
        "react_status": "",
        "available_tool_contracts": "[]",
        "available_tool_summary": "[]",
        "planning_context": {},
        "raw_intent": {},
        "legacy_full_plan": {},
        "raw_plan": {},
        "planner_mode": "",
        "plan_validation": {},
        "execution_plan": {"tasks": []},
        "task_queue": [],
        "current_task": {},
        "task_results": [],
        "completed_tasks": [],
        "time_requirement": {},
        "knowledge_requirement": {},
        "prepared_tool_input": {},
        "route": "direct",
        "risk_level": "low",
        "standalone_query": question,
        "topic": "",
        "entities": [],
        "required_tools": [],
        "candidate_tool": None,
        "selected_tool": None,
        "selected_action": None,
        "tool_input": {},
        "tool_result": {},
        "previous_tool_context": {},
        "current_tool_context": {},
        "time_reference": {},
        "time_context_result": {},
        "time_context_payload": {},
        "needs_time_resolution": False,
        "relative_time": None,
        "missing_required_slots": [],
        "search_tasks": [],
        "pending_search_tasks": [],
        "executed_queries": [],
        "_executed_query_keys": [],
        "_retrieval_cache": {},
        "retrieved_docs": [],
        "sources": [],
        "evidence_brief": "",
        "observations": [],
        "tool_calls": [],
        "evidence_assessment": {},
        "completion_assessment": {},
        "answer_policy": {},
        "rag_answerability": {},
        "reflect_round": 0,
        "final_answer": "",
        "memory_update": {},
        "node_trace": [],
        "llm_calls": [],
        "audit_events": [],
        "skipped_reflection_reason": None,
        "error": None,
    }


__all__ = ["create_initial_state"]
